### ISSUE TITLE
Tracking issue for goridge 3.0

### ISSUE THREAD

**Issue by 48d90782** [spiral/goridge#83]
Branch - 3.0

----
### Planned features:
- [x] Protocol options #87 
- [x] Move PHP source code to the separate repository [Repo](https://github.com/spiral/goridge-php)
- [x] New RPC codecs #88 
- [x] Move pipes and sockets to the new protocol #85 #84 
-----
### Discussion:
- [x] New protocol #96
